import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f5f1eb',
  '--slot4-page-text': '#1b1917',
  '--slot4-panel-bg': '#ede8e0',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#423e3a',
  '--slot4-soft-muted-text': '#8a8580',
  '--slot4-accent': '#c54a0d',
  '--slot4-accent-fill': '#c54a0d',
  '--slot4-accent-soft': '#fdf0e8',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1b1917',
  '--slot4-dark-text': '#f5f1eb',
  '--slot4-media-bg': '#e4e0d9',
  '--slot4-cream': '#f5f1eb',
  '--slot4-warm': '#ede8e0',
  '--slot4-lavender': '#f5f1eb',
  '--slot4-gray': '#e4e0d9',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f5f1eb',
  '--editable-page-text': '#1b1917',
  '--editable-container': '1200px',
  '--editable-border': '#e4e0d9',
  '--editable-nav-bg': '#f5f1eb',
  '--editable-nav-text': '#1b1917',
  '--editable-nav-active': '#c54a0d',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#c54a0d',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1b1917',
  '--editable-footer-text': '#f5f1eb',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_2px_rgba(27,25,23,0.04)]',
  shadowStrong: 'shadow-[0_8px_30px_rgba(27,25,23,0.08)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(27,25,23,0.02),rgba(27,25,23,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-10',
    sectionY: 'py-16 sm:py-20 lg:py-28',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-4 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-[13px] font-medium uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-medium leading-[1.1] tracking-[-0.02em] sm:text-5xl lg:text-[3.75rem]',
    sectionTitle: 'text-3xl font-medium tracking-[-0.02em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-[15px] font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:opacity-90 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3.5 text-[15px] font-medium text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-7 py-3.5 text-[15px] font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:opacity-90 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_12px_40px_rgba(27,25,23,0.1)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the Stoop reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
